steps:
- name: node install
  entrypoint: npm
  args: ["install"]
- name: node run & create-env
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'ENVR=${_ENVR}'
    - 'LOCAL_HOST=${_LOCAL_HOST}'
    - 'REMOTE_HOST=${_REMOTE_HOST}'
    - 'DB_USER=${_DB_USER}'
    - 'DB_NAME=${_DB_NAME}'
    - 'MYSQL_PASSWORD=${_MYSQL_PASSWORD}'
- name: "gcloud app deploy"
  args: ["app", "deploy"]
timeout: "1600s"